server:
  port: 10086

spring:
  datasource:
    url: jdbc:sqlite:./upload-file.db
    driver-class-name: org.sqlite.JDBC
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  main:
    allow-bean-definition-overriding: true

mysql:
  datasource:
    url: ${MYSQL_URL:} # jdbc:mysql://localhost:3306/upload-file?useSSL=false&serverTimezone=Asia/Shanghai
    username: ${MYSQL_USERNAME:} # root
    password: ${MYSQL_PASSWORD:} # root
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    cn.czh.mapper: debug
    org.springframework.jdbc: debug